In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
scalar=tf.constant(7) # creats a tensors
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim # checks number of dimentionns

0

In [ ]:
# create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# create a matrix
matrix=tf.constant([[10,7,8],
              [1,2,4]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  8],
       [ 1,  2,  4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrixa=tf.constant([[1.,5.],
                     [3.,6.],
                     [5.,6.]],dtype=tf.float16)
matrixa

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 5.],
       [3., 6.],
       [5., 6.]], dtype=float16)>

In [ ]:
matrixa.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3,1],
                       [4, 5, 6,2]],
                      [[7, 8, 9,5],
                       [10, 11, 12,9]],
                      [[13, 14, 15,6],
                       [16, 17, 18,4]]])
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  1],
        [ 4,  5,  6,  2]],

       [[ 7,  8,  9,  5],
        [10, 11, 12,  9]],

       [[13, 14, 15,  6],
        [16, 17, 18,  4]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# variables
changeable_tensor=tf.Variable([10,7])    # tf.Variable() tensor
unchangeable_tensor=tf.constant([10,7])  # tf.constant()tensor
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[1]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
changeable_tensor[1]=17

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
changeable_tensor[1].assign(14)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10, 14], dtype=int32)>

In [ ]:
unchangeable_tensor[1]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
unchangeable_tensor[1]=14

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
unchangeable_tensor[1].assign(14)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
# random tensors
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# shuffle a tensor
not_suffled=tf.constant([[10,7],
                         [3,4],
                         [2,5]])
not_suffled.ndim


2

In [ ]:
not_suffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# note**** if u wanna keep constant use globel and operational level
tf.random.set_seed(42)   # globel level seed
tf.random.shuffle(not_suffled,seed=42)   # operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_suffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
var=tf.Variable(7)
const=tf.constant(7)
var,const


(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>,
 <tf.Tensor: shape=(), dtype=int32, numpy=7>)

In [ ]:
# tensor of onees
tf.ones([2,3])


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
# tensor of zeroes
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
a=tf.constant(numpy_A)
a

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
a=tf.constant(numpy_A,shape=(2,3,4)) # matrix
b=tf.constant(numpy_A)   # vector
a,b


(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
a.ndim

3

In [ ]:
#  rank 4 tensor
rank_4_tensor=tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0,1,3,3]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

**Attributes**

In [ ]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print(f"Total number of elements (2*3*4*5):{tf.size(rank_4_tensor)}")
print("Total number of elements (2*3*4*5):",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5):120
Total number of elements (2*3*4*5): 120


In [ ]:
rank_4_tensor[:2,:2,:2,:2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_2_tensor=tf.constant([[10,7],
                         [3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
some_list=[1,2,3,4] # long form in detailed
tf.constant(some_list)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
some_list,some_list[-1] #short cut

([1, 2, 3, 4], 4)

In [ ]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# toadd extra dimention
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# toadd extra dimention
rank_3_tensor_=rank_3_tensor[...,tf.newaxis]
rank_3_tensor_,rank_3_tensor_.ndim

(<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
 array([[[[10]],
 
         [[ 7]]],
 
 
        [[[ 3]],
 
         [[ 4]]]], dtype=int32)>,
 4)

In [ ]:
# alternative method
a=tf.constant([
    [1,2,3],
    [5,6,7]
], dtype=tf.int16)
a.ndim,a.shape

(2, TensorShape([2, 3]))

In [ ]:
a=tf.expand_dims(a,axis=0) # axis= -1 means expand the last axis # axis= 0 means expand the first axis
a.ndim,a.shape

(3, TensorShape([1, 2, 3]))

In [ ]:
a

<tf.Tensor: shape=(2, 3), dtype=int16, numpy=
array([[1, 2, 3],
       [5, 6, 7]], dtype=int16)>

**Basic operation  (+ - / * % )**


In [ ]:
a=tf.constant([[1,2,3],[3,4,5]])
a+10,a*10,a-10,a/10,a%10

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[11, 12, 13],
        [13, 14, 15]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 20, 30],
        [30, 40, 50]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[-9, -8, -7],
        [-7, -6, -5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=float64, numpy=
 array([[0.1, 0.2, 0.3],
        [0.3, 0.4, 0.5]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [3, 4, 5]], dtype=int32)>)

**using inbuilt functions**

In [ ]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [ ]:
tf.add(a,5)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 6,  7,  8],
       [ 8,  9, 10]], dtype=int32)>

In [ ]:
tf.multiply(a,10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [30, 40, 50]], dtype=int32)>

In [ ]:
tf.subtract(a,10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-9, -8, -7],
       [-7, -6, -5]], dtype=int32)>

In [ ]:
tf.divide(a,10)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.1, 0.2, 0.3],
       [0.3, 0.4, 0.5]])>

In [ ]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

**Matrix multiplication**

In [ ]:
m=tf.constant([[1,2],[5,6]])
m

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6]], dtype=int32)>

In [ ]:
tf.matmul(m,m)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 14],
       [35, 46]], dtype=int32)>

In [ ]:
# different output (not matrix multiplicaion)
m*m

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [25, 36]], dtype=int32)>

In [ ]:
# matrix multiplication with python "@"
m@m

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 14],
       [35, 46]], dtype=int32)>

**DOT PRODUCT with tensor and reshape function**

In [ ]:
x=tf.constant([[1,2,3],[4,5,6],[8,9,0]])
y=tf.constant([[1,2],[3,4],[5,6]])
x,y

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [8, 9, 0]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

In [ ]:
x@y,tf.matmul(x,y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[22, 28],
        [49, 64],
        [35, 52]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[22, 28],
        [49, 64],
        [35, 52]], dtype=int32)>)

Reshape in matrix multiplication

*1st example*

In [ ]:
x=tf.constant([[1,2,3],[4,5,6],[8,9,0]])
y=tf.constant([[1,3,5],[7,8,9]])
x,y

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [8, 9, 0]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [7, 8, 9]], dtype=int32)>)

In [ ]:
x@tf.reshape(y,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 35,  44],
       [ 77, 101],
       [ 53,  87]], dtype=int32)>

In [ ]:
tf.transpose(y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 7],
       [3, 8],
       [5, 9]], dtype=int32)>

In [ ]:
x@tf.transpose(y), tf.matmul(x, tf.transpose(y)) # diff answer

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[  7,  25,  17],
        [ 19,  73,  50],
        [ 31, 121,  83]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[  7,  25,  17],
        [ 19,  73,  50],
        [ 31, 121,  83]], dtype=int32)>)

In [ ]:
tf.matmul(x,tf.reshape(y,shape=(3,2)))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 35,  44],
       [ 77, 101],
       [ 53,  87]], dtype=int32)>

*2nd example*

In [ ]:
x=tf.constant([[1,2],[4,5],[7,8]])
y=tf.constant([[1,3],[7,9],[5,6]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 5],
        [7, 8]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 3],
        [7, 9],
        [5, 6]], dtype=int32)>)

In [ ]:
x@tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 13, 19],
       [49, 37, 58],
       [79, 61, 97]], dtype=int32)>

In [ ]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 13, 19],
       [49, 37, 58],
       [79, 61, 97]], dtype=int32)>

Reshapping error

In [ ]:
a=tf.constant([[1,2,3],[6,7,8]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [6, 7, 8]], dtype=int32)>

In [ ]:
tf.reshape(a,shape=(1,2,3,1))

<tf.Tensor: shape=(1, 2, 3, 1), dtype=int32, numpy=
array([[[[1],
         [2],
         [3]],

        [[6],
         [7],
         [8]]]], dtype=int32)>

In [ ]:
tf.reshape(a,shape=(1,2,3))

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [6, 7, 8]]], dtype=int32)>

In [ ]:
tf.reshape(a,shape=(2,3,4))

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 6 values, but the requested shape has 24 [Op:Reshape]

**Matrix multiplication -2**

In [ ]:
x=tf.constant([[1,2],[4,5],[7,8]])
y=tf.constant([[1,3],[7,9],[5,6]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 5],
        [7, 8]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 3],
        [7, 9],
        [5, 6]], dtype=int32)>)

In [ ]:
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  7,  25,  17],
       [ 19,  73,  50],
       [ 31, 121,  83]], dtype=int32)>

In [ ]:
tf.tensordot(x,tf.transpose(y),axes=1) # note it

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  7,  25,  17],
       [ 19,  73,  50],
       [ 31, 121,  83]], dtype=int32)>

**Normal x, reshaped x, transpose x**

In [ ]:
x=tf.constant([[1,2],[4,5],[7,8]])
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)>

In [ ]:
print("Reshaped X : ")
tf.reshape(x,shape=(2,3))

Reshaped X : 


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [5, 7, 8]], dtype=int32)>

In [ ]:
print("transpose X : ")
tf.transpose(x)

transpose X : 


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 5, 8]], dtype=int32)>

Changing **datatypes**



In [ ]:
tf.__version__

'2.15.0'

In [ ]:
import sys
print(sys.version)

3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]


In [ ]:
c=tf.constant([1.,7.,8.6])
c

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 7. , 8.6], dtype=float32)>

In [ ]:
d=tf.cast(c, dtype=tf.float16)
d

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1. , 7. , 8.6], dtype=float16)>

In [ ]:
d.dtype

tf.float16

**Aggregation Tensor**

In [ ]:
a=tf.constant([-7,-10])
a

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(a)  # absolute values

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
import numpy as np


In [ ]:
a=np.random.randint(0,100,size=50)
a

array([66, 49, 36, 52, 27, 34, 81, 10, 77, 83,  8, 10, 85, 92, 48, 39, 68,
       87, 88, 29, 77, 14, 85, 29, 29, 47, 47, 31,  7, 86,  4, 40, 57, 18,
        9, 72, 80,  5, 17, 10, 88, 51, 54, 51, 47, 72, 89, 41, 98, 51])

In [ ]:
a=tf.constant(a)
a

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([66, 49, 36, 52, 27, 34, 81, 10, 77, 83,  8, 10, 85, 92, 48, 39, 68,
       87, 88, 29, 77, 14, 85, 29, 29, 47, 47, 31,  7, 86,  4, 40, 57, 18,
        9, 72, 80,  5, 17, 10, 88, 51, 54, 51, 47, 72, 89, 41, 98, 51])>

In [ ]:
tf.size(a), tf.shape(a), a.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([50], dtype=int32)>,
 1)

In [ ]:
# Find minimum
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
# Find Maximum
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find mean
tf.reduce_mean(a)


<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
# Find sum
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int64, numpy=2475>

In [ ]:
# Find variation  wont work
tf.reduce_variance(a)

AttributeError: module 'tensorflow' has no attribute 'reduce_variance'

In [ ]:
# Find std deviation  wont work
tf.reduce_std(a)

AttributeError: module 'tensorflow' has no attribute 'reduce_std'

**Variance and Standard Deviation**

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(a)

<tf.Tensor: shape=(), dtype=int64, numpy=805>

In [ ]:
tf.math.reduce_variance(tf.cast(a, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=805.01>

In [ ]:
tf.math.reduce_std(a)

TypeError: Input must be either real or complex. Received integer type <dtype: 'int64'>.

In [ ]:
tf.math.reduce_std(tf.cast(a, dtype=tf.float32)) # if complex or real hits use convert it to float32

<tf.Tensor: shape=(), dtype=float32, numpy=28.372698>

**Positional Min or max tensor**

In [ ]:
tf.random.set_seed(42)
a=tf.random.uniform(shape=[50])
a

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

1) Positional Max

In [ ]:
# finding positional maximum
tf.argmax(a)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# checking largest value by above index value
a[tf.argmax(a)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# getting value again
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# checking error and equality
assert a[tf.argmax(a)]==tf.reduce_max(a)

In [ ]:
# comparring max values
a[tf.argmax(a)]==tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

2) Positional min

In [ ]:
# finding positional minimum
tf.argmin(a)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# checking largest value by above index value
a[tf.argmin(a)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
# getting value again
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
# checking error and equality
assert a[tf.argmin(a)]==tf.reduce_min(a)

In [ ]:
# comparring min values
a[tf.argmin(a)]==tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

**Squeezing a tensor (removing all 1-dimension axes)**

In [ ]:
tf.random.set_seed(42)
a=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
a

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
a.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
a_squeez=tf.squeeze(a)
a_squeez,a_squeez.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

**One hot encoding Tensors**

In [181]:
a=[0,1,2,3,4
   ,5]

In [173]:
tf.one_hot(a,depth=6, dtype=tf.int64)

<tf.Tensor: shape=(6, 6), dtype=int64, numpy=
array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])>

In [182]:
tf.one_hot(a, depth=6,on_value="Rohan", off_value="Rk")

<tf.Tensor: shape=(6, 6), dtype=string, numpy=
array([[b'Rohan', b'Rk', b'Rk', b'Rk', b'Rk', b'Rk'],
       [b'Rk', b'Rohan', b'Rk', b'Rk', b'Rk', b'Rk'],
       [b'Rk', b'Rk', b'Rohan', b'Rk', b'Rk', b'Rk'],
       [b'Rk', b'Rk', b'Rk', b'Rohan', b'Rk', b'Rk'],
       [b'Rk', b'Rk', b'Rk', b'Rk', b'Rohan', b'Rk'],
       [b'Rk', b'Rk', b'Rk', b'Rk', b'Rk', b'Rohan']], dtype=object)>

**Explore maths function**

In [184]:
a=tf.range(0,10)
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [185]:
# square
tf.square(a)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [189]:
# Sq-root
tf.sqrt(tf.cast(a, dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [190]:
# log
tf.math.log(tf.cast(a, dtype=tf.float64))

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])>

**Tensors and numpy**

In [191]:
a=tf.constant(np.array([3.,7.,10.]))
a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [192]:
# CONVERT Tensors to numpy
np.array(a), type(np.array(a))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [193]:
a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [194]:
# CONVERT Tensors to numpy
a.numpy(), type(a.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [196]:
b=tf.constant([1.,2.,3.])
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [199]:
b.numpy()

array([1., 2., 3.], dtype=float32)

In [201]:
b.numpy()[0]

1.0

***Finding access to gpu***

In [4]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
!nvidia-smi

Tue Jul 16 17:19:54 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--